from __future__ import annotations

import argparse
import importlib.util
import json
import shutil
import subprocess
import sys
import tempfile
import unittest
import unittest.mock
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
MODULE_PATH = REPO_ROOT / "scripts" / "scaffold-app-repo.py"
FIXTURE_APP_ROOT = REPO_ROOT / "tests" / "fixtures" / "tiny-fixture-app"
SPEC = importlib.util.spec_from_file_location("scaffold_app_repo", MODULE_PATH)
assert SPEC is not None and SPEC.loader is not None
scaffold_app_repo = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = scaffold_app_repo
SPEC.loader.exec_module(scaffold_app_repo)


class ScaffoldAppRepoTests(unittest.TestCase):
    def make_args(self) -> argparse.Namespace:
        return argparse.Namespace(
            repo_root=Path("/tmp/SampleApp"),
            project=Path("SampleApp.xcodeproj"),
            scheme="SampleApp",
            app_target="SampleAppApp",
            ui_test_target="SampleAppUITests",
            scenario_file_name="verify-primary-flow.json",
            scenario_template=Path("/tmp/templates/scenario.json"),
            planner_context_template=Path("/tmp/templates/planner-context.md"),
            simulator_name="iPhone 17 Pro Max",
            simulator_runtime="26.2",
            skip_workflow=False,
        )

    def test_build_refresh_command_preserves_non_default_options(self) -> None:
        command = scaffold_app_repo.build_refresh_command(
            script_path=Path("/opt/ios-ai-ui-check/scripts/scaffold-app-repo.py"),
            repo_root=Path("/tmp/SampleApp"),
            project_relative_path="SampleApp.xcodeproj",
            args=self.make_args(),
            app_target_name="SampleAppApp",
            ui_test_target_name="SampleAppUITests",
        )

        self.assertIn("--repo-root /tmp/SampleApp", command)
        self.assertIn("--project SampleApp.xcodeproj", command)
        self.assertIn("--scheme SampleApp", command)
        self.assertIn("--app-target SampleAppApp", command)
        self.assertIn("--ui-test-target SampleAppUITests", command)
        self.assertRegex(command, r"--scenario-template\s+.+scenario\.json")
        self.assertRegex(
            command,
            r"--planner-context-template\s+.+planner-context\.md",
        )
        self.assertIn("--simulator-name 'iPhone 17 Pro Max'", command)

    def test_build_scaffold_headers_reference_manifest(self) -> None:
        headers = scaffold_app_repo.build_scaffold_headers(
            manifest_relative_path=".github/ai-ui/scaffold-manifest.json",
            source_commit="0123456789abcdef",
        )

        self.assertIn("Source commit: 0123456789ab.", headers["shell"])
        self.assertIn("scaffold-manifest.json", headers["swift"])
        self.assertIn("Generated by ios-ai-ui-check scaffold.", headers["yaml"])
        self.assertIn("Manifest: .github/ai-ui/scaffold-manifest.json.", headers["markdown"])

    def test_build_scaffold_manifest_records_generated_files(self) -> None:
        args = self.make_args()
        manifest = scaffold_app_repo.build_scaffold_manifest(
            repo_root=Path("/tmp/SampleApp"),
            action_repo_root=Path("/opt/ios-ai-ui-check"),
            project_relative_path="SampleApp.xcodeproj",
            scheme_name="SampleApp",
            app_target_name="SampleAppApp",
            ui_test_target_name="SampleAppUITests",
            simulator_name="iPhone 17 Pro Max",
            simulator_runtime="26.2",
            scenario_relative_path=Path(".github/ai-ui/verify-primary-flow.json"),
            scaffold_manifest_relative_path=Path(".github/ai-ui/scaffold-manifest.json"),
            refresh_command="python3 scaffold-app-repo.py --repo-root /tmp/SampleApp --project SampleApp.xcodeproj --scheme SampleApp",
            source_repo="owner/ios-ai-ui-check",
            source_commit="abcdef1234567890",
            generated_files=[
                "scripts/run-ai-ui-scenario.sh",
                ".github/ai-ui/planner-context.md",
            ],
            args=args,
        )

        self.assertEqual(manifest["tool"], "ios-ai-ui-check")
        self.assertEqual(manifest["manifest_version"], 2)
        self.assertEqual(manifest["source_commit"], "abcdef1234567890")
        self.assertEqual(manifest["project_path"], "SampleApp.xcodeproj")
        self.assertEqual(manifest["source_repo"], "owner/ios-ai-ui-check")
        self.assertTrue(manifest["workflow_generated"])
        self.assertIn("scripts/run-ai-ui-scenario.sh", manifest["generated_files"])
        self.assertEqual(
            manifest["refresh_command"],
            "python3 scaffold-app-repo.py --repo-root /tmp/SampleApp --project SampleApp.xcodeproj --scheme SampleApp",
        )

    def test_with_manifest_hashes_records_generated_file_hashes(self) -> None:
        manifest = {"tool": "ios-ai-ui-check"}
        planned_files = [
            scaffold_app_repo.PlannedFile(
                path=Path("/tmp/scripts/run-ai-ui-scenario.sh"),
                relative_path="scripts/run-ai-ui-scenario.sh",
                content="echo hello\n",
            ),
            scaffold_app_repo.PlannedFile(
                path=Path("/tmp/.github/ai-ui/scaffold-manifest.json"),
                relative_path=".github/ai-ui/scaffold-manifest.json",
                content="{}\n",
            ),
        ]

        updated = scaffold_app_repo.with_manifest_hashes(
            scaffold_manifest=manifest,
            planned_files=planned_files,
            scaffold_manifest_relative_path=Path(".github/ai-ui/scaffold-manifest.json"),
        )

        self.assertEqual(updated["manifest_version"], 2)
        self.assertEqual(updated["hash_algorithm"], "sha256")
        self.assertIn("scripts/run-ai-ui-scenario.sh", updated["file_hashes"])
        self.assertNotIn(".github/ai-ui/scaffold-manifest.json", updated["file_hashes"])

    def test_resolve_github_repo_slug_parses_origin_remote(self) -> None:
        with unittest.mock.patch.object(scaffold_app_repo.subprocess, "run") as mock_run:
            mock_run.return_value = unittest.mock.Mock(stdout="git@github.com:owner/ios-ai-ui-check.git\n")

            slug = scaffold_app_repo.resolve_github_repo_slug(Path("/tmp/ios-ai-ui-check"))

        self.assertEqual(slug, "owner/ios-ai-ui-check")

    def test_scaffold_fixture_app_smoke(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo_root = Path(tmp) / "FixtureApp"
            shutil.copytree(FIXTURE_APP_ROOT, repo_root)

            completed = subprocess.run(
                [
                    sys.executable,
                    str(MODULE_PATH),
                    "--repo-root",
                    str(repo_root),
                    "--project",
                    "FixtureApp.xcodeproj",
                    "--scheme",
                    "FixtureApp",
                ],
                cwd=REPO_ROOT,
                check=True,
                capture_output=True,
                text=True,
            )

            self.assertIn("Scaffolded iOS AI UI files", completed.stdout)
            manifest_path = repo_root / ".github" / "ai-ui" / "scaffold-manifest.json"
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            self.assertIn("file_hashes", manifest)
            self.assertIn(
                "Tests/FixtureAppUITests/ScenarioRunnerUITests.swift",
                manifest["file_hashes"],
            )
            self.assertTrue(
                (repo_root / "Tests" / "FixtureAppUITests" / "ScenarioRunnerUITests.swift").exists()
            )
            scheme_text = (
                repo_root
                / "FixtureApp.xcodeproj"
                / "xcshareddata"
                / "xcschemes"
                / "FixtureApp.xcscheme"
            ).read_text(encoding="utf-8")
            self.assertIn("FixtureAppUITests.xctest", scheme_text)


if __name__ == "__main__":
    unittest.main()
